### ISSUE TITLE
[twitter] unable to get user tweets 

### ISSUE THREAD

**Issue by billmetangmo** [medialab/minet#447] opened 2022-09-14 16:35 UTC
Hello,

Thanks for sharing the lib with the community.
I am not able to get user tweets , I got the error:
```
Traceback (most recent call last):
  File "/home/bafou/.local/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/home/bafou/.local/pipx/venvs/minet/lib/python3.8/site-packages/minet/cli/__main__.py", line 198, in main
    to_close = resolve_arg_dependencies(cli_args, config)
  File "/home/bafou/.local/pipx/venvs/minet/lib/python3.8/site-packages/minet/cli/argparse.py", line 290, in resolve_arg_dependencies
    setattr(cli_args, name, value.resolve(config))
  File "/home/bafou/.local/pipx/venvs/minet/lib/python3.8/site-packages/minet/cli/argparse.py", line 253, in resolve
    return getpath(config, self.key, self.default)
  File "/home/bafou/.local/pipx/venvs/minet/lib/python3.8/site-packages/ebbe/utils.py", line 72, in getpath
    target = target[step]
TypeError: string indices must be integers
```
when executing` minet tw user-tweets screen_name  users.csv > tweets.csv` with [users.csv](https://github.com/medialab/minet/files/9568237/users.csv)

Regards.

**Comment by Yomguithereal** [comment] 2022-09-15 07:48
Hello @billmetangmo,

I am unable to reproduce your problem. Can you tell me what is your version of python, minet and ebbe please (I suppose you installed the tool using `pip` and not the standalone version?).

Also can you try upgrading minet and/or ebbe and tell me whether the problem is still there?

**Comment by Yomguithereal** [comment] 2022-09-15 07:57
Another hypothesis: your `.minetrc` file is invalid somehow (can you show it to me after obfuscation of the tokens/keys/secrets so that you don't leak anything precious?)

**Comment by billmetangmo** [comment] 2022-09-15 08:49
I think my .minetrc is valid cause i was able to execute successfullly `minet tw scrape users henkvaness > users.csv` .

Below the versions of the lib I used ( seems to be the lastest available  with Python: 3.8.10
```
minet: 0.61.6
ebbe: 1.9.0
```
I used [pipx ](https://github.com/pypa/pipx)to install minet instaed of pip but I don't think it can be the issue. Or may be ?

**Comment by Yomguithereal** [comment] 2022-09-15 08:55
> I think my .minetrc is valid cause i was able to execute successfullly minet tw scrape users henkvaness > users.csv .

The scrape command does not use the `.minetrc` config at all as it does not need API access. The stack you show is linked to parsing the config, hence my guess. You probably have a bad nesting of the twitter config items. I will add a clearer error if this is the case but I need to confirm this is indeed your problem.

> I used [pipx ](https://github.com/pypa/pipx)to install minet instaed of pip but I don't think it can be the issue. Or may be ?

I agree this should not be an issue.

**Comment by billmetangmo** [comment] 2022-09-15 09:21
Oh , you are right my .minetrc was not good. 
```
---
twitter_api_key: 
twitter_api_secret_key:
twitter_access_token: 
twitter_access_token_secret: 
```

instead of 
```
---
twitter:
  api_key: 
  api_secret_key: 
  access_token: 
  access_token_secret: 
```

Thanks very much.

**Comment by Yomguithereal** [comment] 2022-09-15 09:24
No problem @billmetangmo. I will therefore close this issue and open another one to remind me to display a clear error message to the user for this particular case.

**Closed by Yomguithereal** 2022-09-15 09:24 UTC
Labels: bug

**Comment by tloops329384** [comment] 2023-05-12 08:11
Hi @billmetangmo, just starting on Minet and get problem with finding the minetrc file. I'm using a Debian shell on my windows, and I tried all the command I found to find the minetrc and modify it. Even when I go in the repository, I cannot find any file called minetrc... 
Could you help me finding it ? Thank you so much, I'm totally stuck. 
Tloops

**Comment by Yomguithereal** [comment] 2023-05-12 08:45
@tloops329384 as explained on #700 you actually need to create this file, which is a configuration file. A lot of tools work thusly.
