### ISSUE TITLE
Weird output while scrapping Instagram posts

### ISSUE THREAD

**Issue by florianezanella** [medialab/minet#885] opened 2023-10-11 14:21 UTC
Hi, I used Minet with the following command : "minet instagram user-posts gigilust -c firefox -o output.csv" but in the output a significant number of rows are from another Instagram account and some original posts are missing. 
Can you help me ?

![minet instagram output issue](https://github.com/medialab/minet/assets/115776145/660a4682-fbff-4b70-a544-f21da6357bc7)

**Comment by Yomguithereal** [comment] 2023-10-16 09:38
I am trying to take a look at this and what I seem to see is that there exists posts that are co-posted between two accounts. Currently for instance, the third post here: https://www.instagram.com/gigilust/ is made with another account: https://www.instagram.com/p/Cxig3EhN17X/ (https://www.instagram.com/thegingerchloe/). For missing posts, do you have an example?

**Comment by florianezanella** [comment] 2023-10-23 12:49
Yes, some posts are co-posted, and it seems like the "missing posts" are replaced by posts from accounts that co-posted things with the account I am trying to get the posts from. For example, this is a missing post : https://www.instagram.com/p/Cqx-7EKNHOA/, and this is a post from the other account you mentioned which is in the database (but should not be) : https://www.instagram.com/p/Cq-5RBatzlz/. And there are more "additional posts" than "missing posts", so that the current database includes 550 posts whereas there are actually 353 posts on the account I am interested in.

**Comment by Yomguithereal** [comment] 2023-10-23 14:25
I just pushed some fix consisting of two parts: 1. the post pagination was sometimes erroneous indeed, in presence of coauthored posts & 2. I added a column in the output detailing coauthorship of the post.

This will be available shortly as part of v1.0.0 release of `minet` late this afternoon.

**Comment by florianezanella** [comment] 2023-10-25 16:24
I tried again with the upgraded version, and the problem is solved. Thank you !

I have now another problem, with the comments scrapping (still on Instagram). I used the following command with the latest version of minet : "minet instagram comments https://www.instagram.com/p/CybX4D7oTob/ -c firefox -o output.csv". In the output, the first 86 rows are correct, but then those same comments (and the answers/"child" comments) seem to repeat themselves, and the column "index" is full of nans from the 87th row. 
Can you help me again?
![pb minet](https://github.com/medialab/minet/assets/115776145/aed5670e-3449-45f7-8b4d-41509244c7ed)

**Comment by Yomguithereal** [comment] 2023-10-26 17:05
@florianezanella I just released a v1.0.1 with some attempt to mitigate the problem. Can you test it and tell me what you think? I used the command on my end on the post you indicated and I was able to get 353 unique comments (containing 190 replies). Sometimes the comment pagination switch to not-ranked mode, sometimes to weirdly-arbitrary-ranked mode and I don't know what causes that. In my attempt this means that after comment ranked 116, comments get some weird incremental index again. With some post, the index disappears when reaching unranked comments. This is all very confusing to me but I think this is basically how Instagram's frontend works anyway, so the larger question is whether you feel the result you get is 1. valid, 2. as exhaustive as possible.

I also feel I should rename the `index` column as `ranking` or something of the kind to avoid confusion or drop it altogether, or compute it myself based on the order I actually get the data in.

**Comment by Yomguithereal** [comment] 2023-10-26 17:07
@florianezanella I just released a v1.0.1 with some attempt to mitigate the problem. Can you test it and tell me what you think? I used the command on my end on the post you indicated and I was able to get 353 unique comments (containing 190 replies). Sometimes the comment pagination switch to not-ranked mode, sometimes to weirdly-arbitrary-ranked mode and I don't know what causes that. In my attempt this means that after comment ranked 116, comments get some weird incremental index again. With some post, the index disappears when reaching unranked comments. This is all very confusing to me but I think this is basically how Instagram's frontend works anyway, so the larger question is whether you feel the result you get is 1. valid, 2. as exhaustive as possible (the UI indicates 758 comments, but we must factor in private accounts, deleted/moderated comments etc. I guess).

I also feel I should rename the `index` column as `ranking` or something of the kind to avoid confusion or drop it altogether, or compute it myself based on the order I actually get the data in.

**Comment by florianezanella** [comment] 2023-10-27 10:12
I tried again with the new version and my output contains now 382 unique comments (among a total of 391). I have the same index problem you mentioned after the 116th comment (the index restarts at 15 for no reason). 
In fact, I just need all the comments, plus an indication on whether they are "original" comments or replies. Their "index" is not what I am looking for.
I now have more comments than before, but I still don't understand why the scraping stopped at 382 comments on more than 700 comments. In the output, some comments are either from private accounts or public accounts... So I don't get the part about private accounts...
Thank you for your help.

**Comment by Yomguithereal** [comment] 2023-10-27 11:37
> I tried again with the new version and my output contains now 382 unique comments (among a total of 391).

Does it mean you still have duplicate comments in the output (they must have the same id)?

> So I don't get the part about private accounts...

Are some of those private accounts accounts that you can personally see because they allow you to?

In any case, a true exhaustivity test would be to find a not too commented post and expand/scroll yourself through all comments & replies, count them and compare with the collection made by the command. If those are identical, then there is nothing more we can do and we must accept that the total count of comments given by Instagram might be misleading, false or just that a lot of the comments were deleted or cannot be accessed through the web interface with your user for some reason.

**Comment by florianezanella** [comment] 2023-11-09 15:55
In fact, I was looking at the 'text' duplicates, without thinking that there may be a few comments with the exact same emoji content.
Indeed, there are no more id duplicates.

No, most comments are from private accounts I am not following. Maybe this is a question of authorizations in the settings (which result in some of the private accounts allowing the comments to be extracted, and some not).

I tried with another post (less comments) like you suggested, and it worked. The comments seem to be identical to those under the post, and their number is the same as the one indicated by Instagram. So I guess I will have to conduct my analysis only on a part of the comments under the post I am interested in.

**Comment by Yomguithereal** [comment] 2023-11-09 16:02
> No, most comments are from private accounts I am not following. Maybe this is a question of authorizations in the settings (which result in some of the private accounts allowing the comments to be extracted, and some not).

But are there comments that you are able to read on Instagram's website that are not in the minet extraction? If so, if you are using the same account, this is probably a bug because minet does nothing else than using the same method the site use to display its data.

**Comment by florianezanella** [comment] 2023-11-09 17:12
Yes, there are many comments that appear on Instagram but not in the minet extraction... I don't think that the number of comments indicated by Instagram can be false to the point that they're supposed to be more than 700 but there are actually 391... (and there cannot be 300 deleted comments). So it must be a bug...

**Comment by Yomguithereal** [comment] 2023-11-09 17:17
Can you give me a post that should appear but is absent in minet's output, near the top of the list, that I could plausibly access on my end, so I can debug? If not I am afraid I cannot do much because I won't be able to reproduce without your credentials (and you should not give me your credentials of course).

**Comment by florianezanella** [comment] 2023-11-14 17:13
I think I have understood what is the problem. As you suggested, I tried to find some comments that are on Instagram but not in the minet output. In fact, I have read all the comments displayed under this post and all of them are in the minet output (which means near half of the more-than-700 comments are missing on the page), so it appears that on the computer version of Instagram, only a part of the comments is shown (for this post at least). By contrast, it seems that all the comments are shown on the phone app... So there is no bug with the scrapping apparently...

**Comment by Yomguithereal** [comment] 2023-11-15 09:58
Instagram works in mysterious ways it seems. You wouldn't happen to use a different account on the computer and the phone perchance? In any case I will close this issue for now because there seems to be nothing we can do further.

**Closed by Yomguithereal** 2023-11-15 09:58 UTC
Labels: bug

**Comment by florianezanella** [comment] 2023-11-16 15:52
No, I used the same account on both devices...
Thank you for your help !
